### ISSUE TITLE
"value of the attribute android:value" error

### ISSUE THREAD

**Issue by suriyaa** [iSCApps/isc.apps.android.suriyaa#2]
Want help from @moparisthebest, @skritchz, @copolii, @StephenMilone, @iNoles, @rajukumargupta, @pankajksharma, @Kolesar, @danimt, @QDPeng, @rogermelich, @google and all other Android experts on @GitHub!

---

I got an **value of the attribute "android:value", which is "null" linked to item type can not contain the character "<"** error in Gradle (_`clean build`_) on Android Studio 1.5.1.

---

> Origninal error message (in German):
> 
> ``` gradle
> ...
> :app:generateDebugBuildConfig
> Error:Wert des Attributs "android:value", das mit Elementtyp "null" verknüpft ist, darf nicht das Zeichen "<" enthalten.
> Error:Cannot read packageName from C:\Users\Suriyaa\Documents\GitHub\isc.apps.android.suriyaa\app\src\main\AndroidManifest.xml
> Information:BUILD FAILED
> Information:Total time: 27.75 secs
> Information:2 errors
> ...
> ```
> 
> Translated error message (in English):
> 
> ``` gradle
> ...
> :app:generateDebugBuildConfig
> Error: value of the attribute "android:value", which is "null" linked to item type can not contain the character "<".
> Error:Cannot read packageName from C:\Users\Suriyaa\Documents\GitHub\isc.apps.android.suriyaa\app\src\main\AndroidManifest.xml
> Information:BUILD FAILED
> Information:Total time: 27.75 secs
> Information:2 errors
> ...
> ```

---

Gradle Console shows:

``` gradle
Executing tasks: [:app:generateDebugSources, :app:generateDebugAndroidTestSources]

Configuration on demand is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library
:app:prepareComAndroidSupportSupportV42311Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig
[Fatal Error] :36:24: Wert des Attributs "android:value", das mit Elementtyp "null" verknüpft ist, darf nicht das Zeichen "<" enthalten.


FAILURE: Build failed with an exception.

* What went wrong:
Cannot read packageName from C:\Users\Suriyaa\Documents\GitHub\isc.apps.android.suriyaa\app\src\main\AndroidManifest.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 27.75 secs
```

---

Does somebody now where the error is?

Thanks.

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by iNoles** [comment]
Did you look buildConfigField on build.gradle?

**Comment by suriyaa** [comment]
@iNoles: No. How can I add **`buildConfigField`** in _`build.gradle`_ file?

**Comment by iNoles** [comment]
Another error is in Cannot read packageName from C:\Users\Suriyaa\Documents\GitHub\isc.apps.android.suriyaa\app\src\main\AndroidManifest.xml

**Comment by suriyaa** [comment]
@iNoles: Well I set the **`packageName`** correctly and it still not working.

**Comment by suriyaa** [comment]
Project is no longer maintained.
